### ISSUE TITLE
Teething issue

### ISSUE THREAD

**Issue by guybedford** [bengl/imhotap#1]
Just tried testing this out on Windows and got:

```
$ npm run test

> jspm@3.0.0-beta test C:\Users\guybe\Projects\jspm
> imhotap test/*.js

TAP version 13
1..1
Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:548:9)
    at C:\Users\guybe\Projects\jspm\node_modules\imhotap\lib\exec.js:6:16
    at new Promise (<anonymous>)
    at exec (C:\Users\guybe\Projects\jspm\node_modules\imhotap\lib\exec.js:4:26)
    at C:\Users\guybe\Projects\jspm\node_modules\imhotap\imhotap:52:58
    at C:\Users\guybe\Projects\jspm\node_modules\p-try\index.js:4:10
    at new Promise (<anonymous>)
    at pTry (C:\Users\guybe\Projects\jspm\node_modules\p-try\index.js:3:37)
    at run (C:\Users\guybe\Projects\jspm\node_modules\p-limit\index.js:23:18) {
  errno: 'UNKNOWN',
  code: 'UNKNOWN',
  syscall: 'spawn'
}
```

`test/test.js` contains just `console.log('ok')`. Not sure what I'm doing wrong...

**Comment by guybedford** [comment]
Realize this is likely just my console setup. Windows command testing is way too hard, going with a simple fork workflow instead!
